// layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LangProvider } from "@/app/context/LangContext"; // No need for useLang here
import "./globals.css";
import ClientLangWrapper from "@/components/ClientLangWrapper"; // Import the client-side wrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Noventer",
  description: "Generated by create next app",
  icons: {
    icon: "/NoventerLogo.svg",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <LangProvider> 
      <ClientLangWrapper>
        <body>
          {children}
        </body>
      </ClientLangWrapper>
    </LangProvider>
  );
}
